name: demo-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - jupyter
    - pydot
    - graphviz
    - hls4ml[profiling]
    - matplotlib
    - numpy
    - PyYAML
    - scikit-learn
    - tensorflow
    - tqdm
    - git+https://github.com/google/qkeras#egg=qkeras
    - keras-flops
    # - git+https://github.com/kentaroy47/keras-Opcounter
    - keras-tuner
    - setgpu
    - mplhep
    
